NGZB/Controllers/MenuController.cs
using System.Web.Mvc;
using NGZB.Filter;
using NGZB.Models;
using NGZB.Models.Class;

namespace NGZB.Controllers
{
    [LoginPass]
    [CheckUrl]
    public class MenuController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        //-----------------------分割线，以下为无界面或者为子界面的方法，要添加主界面的方法，在此线以上添加--------------------
        public string __GetMenuGroup()
        {
            return Menu.GetParentMenu(0);
        }

        public int __Del(FormCollection form)
        {
            if (form["menuid"] != null)
            {
                int menuid = 0;
                int.TryParse(form["menuid"], out menuid);
                return Menu.Del(menuid);
            }
            else
            {
                return 0;
            }
        }

        [HttpPost]
        public int __Add(FormCollection form)
        {
            if (form["menuparentID"] == null || form["menuImg"] == null || form["modeid"] == null || form["colercssclass"] == null || form["menutype"] == null)
            {
                return 0;
            }
            else
            {
                int menuparentid = 0;
                int modeid = 0;
                int menutype = 0;
                if (int.TryParse(form["menuparentID"], out menuparentid) == false || int.TryParse(form["modeid"], out modeid) == false)
                {
                    return 0;
                }
                else
                {
                    if (int.TryParse(form["menutype"], out menutype) == false)
                    {
                        menutype = 1;
                    }
                    string menuimg = form["menuImg"].Trim();
                    string colercssclass = form["colercssclass"];
                    return Menu.Add(menuparentid, modeid, menutype, menuimg, colercssclass);
                }
            }
        }

        public string __RoleMenu(FormCollection form)
        {
            if (Request.QueryString["roleid"] != null && Request.QueryString["pid"] != null)
            {
                return Menu.RoleMenu(Request.QueryString["roleid"].ToString(), Request.QueryString["pid"].ToString());
            }
            else
            {
                return "";
            }
        }

        public string __GetParentMenu()
        {
            return Menu.GetParentMenu(0);
        }

        [HttpPost]
        public string __GetMenu(FormCollection form)
        {
            int parentID = 0;
            if (form["parentID"] != null)
            {
                int.TryParse(form["parentID"], out parentID);
                return Menu.GetParentMenu(parentID);
            }
            else
            {
                return "[]";
            }
        }

        [HttpPost]
        public int __AddMenuGroup(FormCollection form)
        {
            if (form["menugroupname"] != null)
            {
                string groupName = form["menugroupname"].ToString().Trim();
                string icon = "my_any";
                if (form["menuImg"] != null)
                {
                    icon = form["menuImg"].ToString().Trim();
                }
                return Menu.AddMenuGroup(groupName, icon);
            }
            else
            {
                return -1;
            }
        }

        public ActionResult _Edit(int? menuid, int? menutype)
        {
            ViewBag.menuID = menuid;
            ViewBag.menuType = menutype;
            return View();
        }

        public int __Edit(int? menuid, int? menutype, int? modelid, string menuimg, int? menuorderby, string menucolor, int? parentid)
        {
            if (menuid == null)
            {
                return -1;
            }
            else
            {
                return Menu.Edit(menuid, menutype, modelid, menuimg, menuorderby, menucolor, parentid);
            }
        }
    }
}

NGZB/Controllers/SysController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NGZB.Filter;
using NGZB.Models;
using NGZB.Models.Class;
using NGZB.Models.Object;

namespace NGZB.Controllers
{
    [LoginPass]
    [CheckUrl]
    public class SysController : Controller
    {
        public ActionResult Help()
        {
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        public ActionResult LoadIcon()
        {
            Sys.LoadIcon(false);
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        public ActionResult LoadModel()
        {
            Sys.LoadMode();
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        public ActionResult OnLineUser()
        {
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        public ActionResult Set()
        {
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        //-----------------------分割线，以下为无界面或者为子界面的方法，要添加主界面的方法，在此线以上添加--------------------

        /// <summary>
        /// 公司名称
        /// </summary>
        /// <returns></returns>
        public static string __CompanyName()
        {
            return Sys.GetInfo("company");
        }

        /// <summary>
        /// 系统easyui主题样式
        /// </summary>
        /// <returns></returns>
        public static string __SystemThems()
        {
            string[] themTemp = { "default", "bootstrap", "gray", "material", "metro", "black", "ui-cupertino", "ui-dark-hive", "ui-pepper-grinder", "ui-sunny" };
            string thems = "";
            try
            {
                thems = Sys.GetInfo("systemthems");
            }
            catch
            {
                thems = "default";
            }
            if(thems == "")
            {
                return "default";
            }
            else
            {
                var quere = from _them in themTemp
                            where _them == thems
                            select _them;
                if(!quere.Any())
                {
                    thems = "default";
                }
                return thems;
            }
        }

        /// <summary>
        /// 按钮样式，平面或者立体
        /// </summary>
        /// <returns></returns>
        public static string __ThemsType()
        {
            string thems = Sys.GetInfo("themstype");
            if(thems == "")
            {
                return "true";
            }
            else
            {
                return thems;
            }
        }

        /// <summary>
        /// 允许上传文件的类型
        /// </summary>
        /// <returns></returns>
        public static string __UpFileType()
        {
            string upfiletype = Sys.GetInfo("upfiletype");
            if(upfiletype == "")
            {
                return "'.jpg', '.png', '.rar', '.txt', '.zip', '.doc', '.ppt', '.xls', '.pdf', '.docx', '.xlsx', '.docx'";
            }
            else
            {
                return upfiletype;
            }
        }

        /// <summary>
        /// 允许上传文件的大小
        /// </summary>
        /// <returns></returns>
        public static int __UpFileMax()
        {
            string _upfilemaxsize = Sys.GetInfo("upfilemaxsize");
            int upfilemaxsize = 0;
            if(int.TryParse(_upfilemaxsize, out upfilemaxsize) == false)
            {
                upfilemaxsize = 4;
            }
            return upfilemaxsize;
        }

        /// <summary>
        /// 首页显示新文件数量
        /// </summary>
        /// <returns></returns>
        public static int __NewFileListCount()
        {
            string newfilelistcount = Sys.GetInfo("newfilelistcount");
            int rowcount = 0;
            int.TryParse(newfilelistcount, out rowcount);
            if(rowcount == 0)
            {
                return 10;
            }
            else
            {
                if(rowcount > 50)
                {
                    return 50;
                }
                return 10 * (rowcount / 10);
            }
        }

        /// <summary>
        /// 首页显示公共数量
        /// </summary>
        /// <returns></returns>
        public static int __MessageListCount()
        {
            string messagelistcount = Sys.GetInfo("messagelistcount");
            int rowcount = 0;
            int.TryParse(messagelistcount, out rowcount);
            if(rowcount == 0)
            {
                return 10;
            }
            else
            {
                if(rowcount > 50)
                {
                    return 50;
                }
                return 10 * (rowcount / 10);
            }
        }

        /// <summary>
        /// 是否允许所有人发布功能
        /// </summary>
        /// <returns></returns>
        public static int __MessageAllowType()
        {
            int rt = 0;
            int.TryParse(Sys.GetInfo("allowmessage"), out rt);
            return rt;
        }

        /// <summary>
        /// 是否隐藏文件描述
        /// </summary>
        /// <returns></returns>
        public static string __FileInfoHidden()
        {
            string _tempstr = Sys.GetInfo("fileinfohidden");
            if(_tempstr == "")
            {
                return "true";
            }
            else
            {
                return _tempstr;
            }
        }

        /// <summary>
        /// 表格分页大小
        /// </summary>
        /// <returns></returns>
        public static int __PageSize()
        {
            int pageSize = 30;
            string _tempstr = "30";
            try
            {
                _tempstr = Sys.GetInfo("datagridpagesize");
            }
            catch
            {
                _tempstr = "30";
            }
            int.TryParse(_tempstr, out pageSize);
            if(pageSize == 0)
            {
                pageSize = 30;
            }
            return pageSize;
        }

        /// <summary>
        /// 是否禁止鼠标默认右键
        /// </summary>
        /// <returns></returns>
        public static int __EnableRightBtn()
        {
            string _tempstr = "";
            try
            {
                _tempstr = Sys.GetInfo("enablerightbtn");
            }
            catch
            {
                _tempstr = "0";
            }
            int rt = 0;
            if(int.TryParse(_tempstr, out rt) == false || rt != 1)
            {
                rt = 0;
            }
            else
            {
                rt = 1;
            }
            return rt;
        }

        /// <summary>
        /// 是否压缩css和js文件
        /// </summary>
        /// <returns></returns>
        public static bool __EnabelZipCssAndJs()
        {
            string _tempstr = "";
            try
            {
                _tempstr = Sys.GetInfo("enablezipcssjs");
            }
            catch
            {
                _tempstr = "1";
            }
            bool rt = true;
            if(_tempstr != "1")
            {
                rt = false;
            }
            return rt;
        }

        public static string __CopyRight()
        {
            string _tempstr = Sys.GetInfo("copyright");
            return _tempstr;
        }

        public static int __MsgAnsyTime()
        {
            string _tempstr = Sys.GetInfo("msgansytime");
            int time = 0;
            int.TryParse(_tempstr, out time);
            return time * 60000;
        }

        /// <summary>
        /// 设备树加载是否开启异步加载，由系统自动更新维护
        /// </summary>
        /// <returns></returns>
        public static bool __EqIsAnsy()
        {
            string _tempstr = Sys.GetInfo("eqisansy");
            return _tempstr.ToLower() == "true" ? true : false;
        }

        public static string __IconAlign()
        {
            string _tempstr = Sys.GetInfo("iconalign").ToLower();
            if(_tempstr == "top" || _tempstr == "right" || _tempstr == "left" || _tempstr == "bottom")
            {
                return _tempstr;
            }
            else
            {
                return "left";
            }
        }

        public static int __AllowOpenTabNum()
        {
            string _tempstr = Sys.GetInfo("allowtabnum").ToLower();
            int tabnum = 8;
            int.TryParse(_tempstr, out tabnum);
            if(tabnum == 0)
            {
                tabnum = 8;
            }
            return tabnum;
        }

        public static object __TokenKey()
        {
            LoginUser loginuser = new LoginUser();
            return new { tokenkey = loginuser.Tokenkey };
        }

        public static string __TokenKeyStr()
        {
            LoginUser loginuser = new LoginUser();
            return loginuser.Tokenkey;
        }

        public static int __CookiesTime()
        {
            string _tempstr = Sys.GetInfo("cookiestime");
            int _rt = 30;
            int.TryParse(_tempstr, out _rt);
            if(_rt == 0)
            {
                _rt = 7
;
            }
            return _rt;
        }

        public static string __PublishTool()
        {
            return "tools:'#publishtool'";
        }

        public static string __SystemTitle()
        {
            return Sys.GetInfo("systemtitle");
        }

        [HttpPost]
        public string __GetModel(FormCollection form)
        {
            if(form["c"] != null)
            {
                if(form["key"] != null)
                {
                    return Sys.GetModel(form["c"], form["key"]);
                }
                else
                {
                    return Sys.GetModel(form["c"], null);
                }
            }
            else
            {
                if(form["key"] != null)
                {

NGZB/Views/Menu/Index.cshtml
@using NGZB.Controllers
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>自动化系统模块管理</title>
    @Html.Partial("_JsCss")
    @{ var objTokenKey = SysController.__TokenKey(); }
    <script type="text/javascript">
        var url_getmenumodel = '@Url.Action("__GetMenuModel", "Sys",objTokenKey)';
        var url_add = '@Url.Action("__Add","Menu", objTokenKey)';
        var url_del = '@Url.Action("__Del","Menu", objTokenKey)';
        var url_addmenugroup = '@Url.Action("__AddMenuGroup","Menu", objTokenKey)';
        var url_edit = '@Url.Action("_Edit", "Menu", objTokenKey)';
    </script>
</head>
<body style="width:100%;">
    <table id="tt" class="easyui-datagrid" style="width:100%"
           title="菜单管理"
           url="@Url.Action("__GetMenu","Menu", objTokenKey)"
           singleSelect="true"
           data-options="@SysController.__PublishTool(),iconCls:'icon-my_menu',fit:true,toolbar:'#tb',pagination:true,pageSize:@SysController.__PageSize(),loadFilter:pagerFilter,fitColumns:true,onLoadSuccess:function(data){formatlinbutton(data);},striped:true,border:false, onDblClickRow: function (index, row) {showEdit(index,row);} ">
        <thead>
            <tr>
                <th field="menuID" align="center" width="60">菜单ID</th>
                <th field="menuName" align="center" width="100">菜单名称</th>
                <th field="menuInfo" width="400" halign="center" align="left">功能描述</th>
                <th field="menuType" width="60" halign="center" align="center" data-options="formatter:cellStyler">菜单权限</th>
                <th field="menuOrderBy" width="40" halign="center" align="center">排序</th>
                <th field="_thems" width="60" halign="center" align="center" data-options="formatter:themsformat">最终样式</th>
                <th field="_del" width="50" halign="center" align="center" data-options="formatter:delformat">删除</th>
            </tr>
        </thead>
    </table>
    <div id="tb">
        <div style="margin:2px;">
            <div class="easyui-linkbutton mylabel" data-options="plain:true,iconCls:'icon-my_searckkey'" onclick="showAddMenuGroup()">菜单分组:</div>
            <input id="menugroup" class="easyui-combobox" name="language" style="width:120px" data-options="url:'@Url.Action("__GetParentMenu", "Menu", objTokenKey)',onChange:function(newValue,oldValue){search(newValue);},method:'get',valueField:'menuID', textField:'menuName', panelHeight:'auto'">
            <div class="easyui-linkbutton mylabel" data-options="plain:true,iconCls:'icon-my_controller'">选择模块:</div>
            <input id="controller" class="easyui-combobox" name="language" style="width:120px" data-options="url:'@Url.Action("__GetController", "Sys", objTokenKey)',method:'get', valueField:'modelControllers', textField:'modelControllers', panelHeight:'auto',onChange:function(newValue,oldValue){search();} ">
            <div class="easyui-linkbutton mylabel" data-options="plain:true,iconCls:'icon-my_plugin'">可添加功能:</div>
            <input id="action" class="easyui-combobox" style="width:100px" data-options="url:'@Url.Action("__GetMenuModel", "Sys", objTokenKey)', method:'get', valueField:'modelID', textField:'modelName', panelHeight:'auto'">
            <div class="easyui-linkbutton mylabel" data-options="plain:true,iconCls:'icon-my_icons'">菜单图标:</div>
            @Html.Partial("_IconSelect", new ViewDataDictionary { { "w", "200" }, { "btn", "iconthemsbtn" } })
            <div class="easyui-linkbutton mylabel" data-options="plain:true,iconCls:'icon-my_colors'">附加颜色:</div>
            @Html.Partial("_ColorSelect", ViewData["btn"] = "iconthemsbtn")
            <div class="easyui-linkbutton mylabel" data-options="plain:true,iconCls:'icon-my_key'">权限:</div>
            <select id="menutype" class="easyui-combobox" name="state" style="width:60px;" data-options="panelHeight:'auto'">
                <option value="0">公共</option>
                <option value="1">授权</option>
            </select>
            <a id="iconthemsbtn" class="easyui-linkbutton" data-options="plain:@SysController.__ThemsType(),iconCls:'icon-add'" style="width:80px" onclick="addmenu()">添加菜单</a>
        </div>
    </div>
    <div id="addgroup" style="padding:5px 5px 5px 10px;display:none;overflow:hidden">
        <table cellpadding="5">
            <tr>
                <td>分组名称:</td>
                <td><input id="groupname" style="width:160px" class="easyui-textbox" type="text" name="name" data-options="required:false" /></td>
            </tr>
        </table>
        <div style="text-align:center;padding:5px">
            <a href="javascript:;" class="easyui-linkbutton" onclick="addMenuGroup();" data-options="plain:@SysController.__ThemsType(),iconCls:'icon-add'">添加分组</a>
        </div>
    </div>
    @Html.Partial("_PublishTool")
    <script src="~/JsApp/Menu/index.js"></script>
</body>
</html>

NGZB/Views/Menu/_Edit.cshtml
@using NGZB.Controllers
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Html.Partial("_JsCss")
    @{ var objTokenKey = SysController.__TokenKey(); }
    <title>菜单修改</title>
    <script>
        var url_getmenumodel = '@Url.Action("__GetMenuModel", "Sys",objTokenKey)';
        var url_edit = '@Url.Action("__Edit","Menu",objTokenKey)';
    </script>
</head>
<body>
    <div style="text-align:center;padding-left:10px;padding-top:10px">
        <table style="text-align:left">
            <tr>
                <td style="word-break:break-word;white-space:nowrap">菜单ID</td>
                <td>
                    <input id="menuid" style="width:80px" class="easyui-textbox" type="text" disabled="disabled" value="@ViewBag.menuID" data-options="required:false" />
                </td>
                <td>菜单排序</td>
                <td>
                    <input id="menuorderby" style="width:80px" class="easyui-textbox" type="text" />
                </td>
            </tr>
            <tr>
                <td style="word-break:break-word;white-space:nowrap">菜单分组</td>
                <td>
                    <input id="menugroup" class="easyui-combobox" name="language" style="width:120px" data-options="url:'@Url.Action("__GetParentMenu", "Menu", objTokenKey)',onChange:function(newValue,oldValue){search(newValue);},method:'get',valueField:'menuID', textField:'menuName', panelHeight:'auto'">
                </td>
                <td style="word-break:break-word;white-space:nowrap">菜单权限</td>
                <td>
                    <select id="menutype" class="easyui-combobox" name="state" style="width:80px;" data-options="panelHeight:'auto'">
                        <option value="0">公共</option>
                        <option value="1">授权</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>选择模块</td>
                <td>
                    <input id="controller" class="easyui-combobox" name="language" style="width:120px" data-options="url:'@Url.Action("__GetController", "Sys", objTokenKey)',
                   method:'get', valueField:'modelControllers', textField:'modelControllers', panelHeight:'auto',onChange:function(newValue,oldValue){search(newValue);} ">
                </td>
                <td style="word-break:break-word;white-space:nowrap">选择功能</td>
                <td>
                    <input id="action" class="easyui-combobox" style="width:100px" data-options="url:'@Url.Action("__GetMenuModel", "Sys", objTokenKey)',
                   method:'get', valueField:'modelID', textField:'modelName', panelHeight:'auto'">
                </td>
            </tr>
            <tr>
                <td style="word-break:break-word;white-space:nowrap">菜单图标</td>
                <td>
                    @Html.Partial("_IconSelect", new ViewDataDictionary { { "w", "180" }, { "btn", "iconthemsbtn" } })
                </td>
                <td style="word-break:break-word;white-space:nowrap">附加颜色</td>
                <td>
                    @Html.Partial("_ColorSelect", ViewData["btn"] = "iconthemsbtn")
                </td>
            </tr>
            <tr>
                <td colspan="4" style="text-align:center;padding-top:20px">
                    <a id="iconthemsbtn" class="easyui-linkbutton" data-options="plain:@SysController.__ThemsType(),iconCls:'icon-edit'" style="width:80px" onclick="editMenu()">修改菜单</a>
                </td>
            </tr>
            <tr>
                <td colspan="4" style="text-align:left;padding-top:30px;color:red">
                    说明：如果菜单权限由授权变更为公共，将自动删除该菜单的授权用户;如果有公共菜单变成授权，则需要为该菜单添加授权用户;不需要修改的项目内容为空即可。
                </td>
            </tr>
        </table>
        <input id="menutypevalue" type="hidden" value="@ViewBag.menuType" />
    </div>
    <script src="~/JsApp/Menu/_edit.js"></script>
</body>
</html>