NGZB/Models/MyMsg.cs
using System.Data;
using Newtonsoft.Json;
using NGZB.Models.Class;

namespace NGZB.Models
{
    public class MyMsg
    {
        public static string MsgBox(string userCode, string msgBox)
        {
            string where = "";
            if (msgBox.ToLower() == "send")
            {
                where = string.Format("sendUserCode='{0}'", userCode);
            }
            else
            {
                where = string.Format("recUserCode='{0}'", userCode);
            }
            DataTable dt = DbHelp.ExcuteTable("SELECT [personMsgID],[msgtitle],[msgInfo],[sendUserCode],[recUserCode],CONVERT(varchar(16),[sendDate],120) AS [sendDate],CONVERT(varchar(16),[readDate],120) AS [readDate],[readState],[fileUrl],[sendUserName],[recUserName] FROM [V_NGZB_PersonMsg]", where, null);
            return JsonConvert.SerializeObject(dt);
        }

        public static int SendMessage(string msgtitle, string msginfo, string sendUserCode, string[] recUserCode, string fileUrl)
        {
            ctxDbDataContext ctx = new ctxDbDataContext();
            int? rt = 0;
            int suc = 0;
            for (int i = 0; i < recUserCode.Length; i++)
            {
                ctx.I_NGZB_PersonMsg(msgtitle, msginfo, sendUserCode, recUserCode[i], fileUrl, ref rt);
                if (rt == 1)
                {
                    suc++;
                }
            }
            return suc;
        }

        public static string GetMsgInfo(int personMsgID, string userCode)
        {
            string where = string.Format("personMsgID={0} AND (recUserCode='{1}' OR sendUserCode='{2}')", personMsgID, userCode, userCode);
            return DbHelp.GetDbItem("NGZB_PersonMsg", "msgInfo", where, null);
        }

        public static int GetNoReadMsg(int personMsgID, string userCode)
        {
            string isread = string.Format("personMsgID={0} AND [readState]=0", personMsgID);
            if (DbHelp.SearchNum("NGZB_PersonMsg", isread) > 0)
            {
                string upsql = string.Format("UPDATE NGZB_PersonMsg SET [readDate] = GETDATE(),[readState] = 1 WHERE [personMsgID]={0}", personMsgID);
                DbHelp.ExcuteNoQuery(upsql);
            }
            string noreadSqlWhere = string.Format("[recUserCode]='{0}' AND readState=0", userCode);
            return DbHelp.SearchNum("NGZB_PersonMsg", noreadSqlWhere);
        }

        public static string GetUserGroup(int groupID, string selfUserCode)
        {
            string where = string.Format("userIsDelFlag=0 AND groupID={0} AND userCode<>'{1}'", groupID, selfUserCode);
            DataTable dt = DbHelp.ExcuteTable("SELECT userCode,userName FROM NGZB_User", where, null);
            return JsonConvert.SerializeObject(dt);
        }

        public static int DelMsg(string[] msgid, string userCode, string delType)
        {
            int suc = 0;
            int _msg = 0;
            string delusercode = "";
            if (delType == "R")
            {
                delusercode = "recUserCode";
            }
            else
            {
                delusercode = "sendUserCode";
            }
            for (int i = 0; i < msgid.Length; i++)
            {
                string delsql = "";
                if (int.TryParse(msgid[i], out _msg) == true)
                {
                    delsql = string.Format("UPDATE NGZB_PersonMsg SET {0}=NULL WHERE personMsgID={1}", delusercode, _msg);
                    if (DbHelp.ExcuteNoQuery(delsql) > 0)
                    {
                        suc = suc + 1;
                    }
                }
            }
            return suc;
        }

        public static string MsgBox(string userCode, string msgBox, string key, string st, string et, int readtype)
        {
            string where = "";
            if (msgBox == "send")
            {
                where = string.Format("(sendUserCode='{0}') AND (msgtitle LIKE '%{1}%' OR msgInfo LIKE '{2}' OR recUserName LIKE '%{3}%') AND (sendDate BETWEEN '{4}'  AND '{5}') AND (readState={6})", userCode, key, key, key, st, et, readtype);
            }
            else
            {
                where = string.Format("(recUserCode='{0}') AND (msgtitle LIKE '%{1}%' OR msgInfo LIKE '{2}' OR sendUserName LIKE '%{3}%') AND (sendDate BETWEEN '{4}'  AND '{5}') AND (readState={6})", userCode, key, key, key, st, et, readtype);
            }
            DataTable dt = DbHelp.ExcuteTable("SELECT [personMsgID],[msgtitle],[msgInfo],[sendUserCode],[recUserCode],CONVERT(varchar(16),[sendDate],120) AS [sendDate],CONVERT(varchar(16),[readDate],120) AS [readDate],[readState],[fileUrl],[sendUserName],[recUserName] FROM [V_NGZB_PersonMsg]", where, null);
            return JsonConvert.SerializeObject(dt);
        }
    }
}

NGZB/Controllers/MyMsgController.cs
using System;
using System.Web.Mvc;
using NGZB.Filter;
using NGZB.Models;
using NGZB.Models.Class;

namespace NGZB.Controllers
{
    [LoginPass]
    [CheckUrl]
    public class MyMsgController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        //-----------------------分割线，以下为无界面或者为子界面的方法，要添加主界面的方法，在此线以上添加--------------------

        public string __GetUser()
        {
            if (Request.QueryString["groupid"] != null)
            {
                int groupID = 0;
                int.TryParse(Request.QueryString["groupid"], out groupID);
                Models.Class.SessionHelp session = new Models.Class.SessionHelp();
                string loginUserCode = session.GetSessionUser();
                return MyMsg.GetUserGroup(groupID, loginUserCode);
            }
            else
            {
                return "[]";
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public int __SendMessage(FormCollection form)
        {
            string msgtitle = "";
            if (form["msgtitle"] != null)
            {
                msgtitle = form["msgtitle"];
            }
            else
            {
                return 0;
            }
            string msginfo = "";
            if (form["msginfo"] != null)
            {
                msginfo = form["msginfo"];
            }
            string[] recUsercode = null;
            if (form["recUsercode"] != null)
            {
                recUsercode = form["recUsercode"].Split('|');
            }
            else
            {
                return 0;
            }
            if (recUsercode != null)
            {
                string fileUrl = "";//预留附件功能
                if (recUsercode.Length > 0)
                {
                    Models.Class.SessionHelp session = new Models.Class.SessionHelp();
                    string loginUserCode = session.GetSessionUser();
                    return MyMsg.SendMessage(msgtitle, msginfo, loginUserCode, recUsercode, fileUrl);
                }
                else
                {
                    return 0;
                }
            }
            else
            {
                return 0;
            }
        }

        public string _GetMsgInfo()
        {
            if (Request.QueryString["personMsgID"] != null)
            {
                int personMsgID = 0;
                int.TryParse(Request.QueryString["personMsgID"], out personMsgID);
                Models.Class.SessionHelp session = new Models.Class.SessionHelp();
                string loginUserCode = session.GetSessionUser();
                return MyMsg.GetMsgInfo(personMsgID, loginUserCode);
            }
            else
            {
                return "";
            }
        }

        public int __GetNoReadMsg()
        {
            int personMsgID = 0;
            Models.Class.SessionHelp session = new Models.Class.SessionHelp();
            string loginUserCode = session.GetSessionUser();
            if (Request.QueryString["personMsgID"] != null)
            {
                int.TryParse(Request.QueryString["personMsgID"], out personMsgID);
            }
            else
            {
                return 0;
            }
            int noread = MyMsg.GetNoReadMsg(personMsgID, loginUserCode);
            return noread;
        }

        public int __DelRecMsg(FormCollection form)
        {
            if (form["msgid"] != null)
            {
                string[] msgid = form["msgid"].Split('|');
                if (msgid.Length > 0)
                {
                    Models.Class.SessionHelp session = new Models.Class.SessionHelp();
                    string loginUserCode = session.GetSessionUser();
                    return MyMsg.DelMsg(msgid, loginUserCode, "R");
                }
                else
                {
                    return 0;
                }
            }
            else
            {
                return -1;
            }
        }

        public int __DelSendMsg(FormCollection form)
        {
            if (form["msgid"] != null)
            {
                string[] msgid = form["msgid"].Split('|');
                if (msgid.Length > 0)
                {
                    Models.Class.SessionHelp session = new Models.Class.SessionHelp();
                    string loginUserCode = session.GetSessionUser();
                    return MyMsg.DelMsg(msgid, loginUserCode, "S");
                }
                else
                {
                    return 0;
                }
            }
            else
            {
                return -1;
            }
        }

        [HttpPost]
        public string __RecMsgBox(FormCollection form)
        {
            string keys = "";
            DateTime _st = DateTime.Now.AddDays(-7);
            DateTime _et = DateTime.Now;
            int readtype = -1;
            if (form["keys"] != null)
            {
                keys = form["keys"];
            }
            if (form["sdate"] != null)
            {
                if (DateTime.TryParse(form["sdate"], out _st) == false)
                {
                    _st = DateTime.Now.AddDays(-7);
                }
            }
            if (form["edate"] != null)
            {
                if (DateTime.TryParse(form["edate"], out _et) == false)
                {
                    _et = DateTime.Now;
                }
            }
            if (form["readtype"] != null)
            {
                int.TryParse(form["readtype"], out readtype);
            }
            Models.Class.SessionHelp session = new Models.Class.SessionHelp();
            string loginUserCode = session.GetSessionUser();
            if (readtype != -1)
            {
                string st = _st.ToShortDateString() + " 00:00";
                string et = _et.ToShortDateString() + " 23:59";
                return MyMsg.MsgBox(loginUserCode, "rec", keys, st, et, readtype);
            }
            else
            {
                return MyMsg.MsgBox(loginUserCode, "rec");
            }
        }

        [HttpPost]
        public string __SendMsgBox(FormCollection form)
        {
            string keys = "";
            DateTime _st = DateTime.Now.AddDays(-7);
            DateTime _et = DateTime.Now;
            int readtype = -1;
            if (form["keys"] != null)
            {
                keys = form["keys"];
            }
            if (form["sdate"] != null)
            {
                if (DateTime.TryParse(form["sdate"], out _st) == false)
                {
                    _st = DateTime.Now.AddDays(-7);
                }
            }
            if (form["edate"] != null)
            {
                if (DateTime.TryParse(form["edate"], out _et) == false)
                {
                    _et = DateTime.Now;
                }
            }
            if (form["readtype"] != null)
            {
                int.TryParse(form["readtype"], out readtype);
            }
            Models.Class.SessionHelp session = new Models.Class.SessionHelp();
            string loginUserCode = session.GetSessionUser();
            if (readtype != -1)
            {
                string st = _st.ToShortDateString() + " 00:00";
                string et = _et.ToShortDateString() + " 23:59";
                return MyMsg.MsgBox(loginUserCode, "send", keys, st, et, readtype);
            }
            else
            {
                return MyMsg.MsgBox(loginUserCode, "send");
            }
        }
    }
}

NGZB/Views/MyMsg/Index.cshtml
@using NGZB.Controllers
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>我的消息</title>
    @Html.Partial("_JsCss")
    @{ var objTokenKey = SysController.__TokenKey(); }
    <script>
        var url_getuser = '@Url.Action("__GetUser", "MyMsg",objTokenKey)';
        var url_sendmessage = '@Url.Action("__SendMessage","MyMsg", objTokenKey)';
        var url_getmsginfo = '@Url.Action("_GetMsgInfo", "MyMsg",objTokenKey)';
        var url_getnoreadmsg = '@Url.Action("__GetNoReadMsg", "MyMsg",objTokenKey)';
        var url_delrecmsg = '@Url.Action("__DelRecMsg","MyMsg", objTokenKey)';
        var url_delsendmsg = '@Url.Action("__DelSendMsg", "MyMsg",objTokenKey)';
    </script>
</head>
<body>
    <div id="tabs" class="easyui-tabs" data-options="fit:true,border:false">
        <div title="收件箱" style="padding:2px">
            <table id="recbox" class="easyui-datagrid" style="width:100%;height:100%"
                   data-options="singleSelect:false,collapsible:false,url:'@Url.Action("__RecMsgBox", "MyMsg",objTokenKey)',method:'post',fit:true,toolbar:'#tb1',fitColumns:true,nowrap:false,striped:true,pagination:true,pageSize:@SysController.__PageSize(),loadFilter:pagerFilter,border:false">
                <thead>
                <thead>
                    <tr>
                        <th data-options="field:'ck',checkbox:true" align="center"></th>
                        <th data-options="field:'personMsgID',width:60,align:'center'">ID</th>
                        <th data-options="field:'msgtitle',width:500,halign:'center',align:'left',formatter:titleformat">消息标题</th>
                        <th data-options="field:'sendUserName',width:80,align:'center'">发送人</th>
                        <th data-options="field:'sendDate',width:110,align:'center'">发送时间</th>
                        <th data-options="field:'readState',width:60,align:'center',formatter:textFormat,styler:cellStyler">阅读状态</th>
                        <th data-options="field:'fileUrl',width:60,align:'center'">附件</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div title="发件箱" style="padding:2px">
            <table id="sendbox" class="easyui-datagrid" style="width:100%;height:100%"
                   data-options="singleSelect:false,collapsible:false,url:'@Url.Action("__SendMsgBox", "MyMsg", objTokenKey)',method:'post',fit:true,toolbar:'#tb2',fitColumns:true,nowrap:false,striped:true,pagination:true,loadFilter:pagerFilter,pageSize:20,border:false">
                <thead>
                <thead>
                    <tr>
                        <th data-options="field:'ck',checkbox:true" align="center"></th>
                        <th data-options="field:'personMsgID',width:60,align:'center'">ID</th>
                        <th data-options="field:'msgtitle',width:500,halign:'center',align:'left',formatter:titleformatsend">消息标题</th>
                        <th data-options="field:'recUserName',width:80,align:'center'">接收人</th>
                        <th data-options="field:'readDate',width:110,align:'center'">阅读时间</th>
                        <th data-options="field:'readState',width:60,align:'center',formatter:textFormat,styler:cellStyler">阅读状态</th>
                        <th data-options="field:'fileUrl',width:60,align:'center'">附件</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div title="发送信息">
            <table style="width:100%;margin-top:5px">
                <tr>
                    <td class="rightTD">消息标题:</td>
                    <td class="leftTD" style="padding-left:20px">
                        <input id="messagetitle" class="easyui-textbox" type="text" name="name" data-options="required:true" style="width:400px" />
                    </td>
                </tr>
                <tr>
                    <td class="rightTD">选择收件人:</td>
                    <td class="leftTD" style="padding-left:20px">
                        @Html.Partial("_Department")
                        <input class="easyui-combobox" id="usercode" data-options="multiple:true,valueField:'userCode',textField:'userName',panelHeight:'auto',iconCls:'icon-man',panelWidth:'80px'" style="width:200px">
                        <div class="fa fa-file-text-o mylabel"> 多选可以同时发送给多人,选择以后在空白区域点击收回选择框</div>
                    </td>
                </tr>
                <tr>
                    <td class="rightTD">消息内容:</td>
                    <td class="leftTD" style="padding-left:20px;padding-right:20px;">@Html.Partial("_SimpleEdit", new ViewDataDictionary { { "id", "kedit" }, { "h", "480px" }, { "t", "0" } })</td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:center">
                        <a id="add" class="easyui-linkbutton c1" data-options="iconCls:'icon-add'" style="width:80px;margin-top:10px" onclick="sendmessage()">发送消息</a>
                        <a id="cls" class="easyui-linkbutton c5" data-options="iconCls:'icon-clear'" style="width:80px;margin-left:80px" onclick="clearmessage()">清空内容</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div id="tb1" style="text-align:center">
        <div style="margin:2px">
            <div class="fa fa-file-text-o mylabel"> 输入消息标题、内容或者接收者关键字：</div>
            <input id="searchreckey" class="easyui-textbox" style="width:200px;height:25px">
            <div class="fa fa-filter mylabel" data-options="plain:true">接收时间从：</div>
            @Html.Partial("_DateSelect", new ViewDataDictionary { { "id", "st1" }, { "d", "-7" } })
            <div class="fa fa-filter mylabel" data-options="plain:true">到：</div>
            @Html.Partial("_DateSelect", ViewData["id"] = "et1")
            <select id="readtype1" class="easyui-combobox" name="state" style="width:80px" data-options="panelHeight:'auto'">
                <option value="-1">全部</option>
                <option value="1">已读</option>
                <option value="0">未读</option>
            </select>
            <a href="javascript:searchRecBox();" class="easyui-linkbutton c2" iconCls="icon-search" plain="@SysController.__ThemsType()" style="margin-left:10px">查询</a>
            <a href="javascript:delMsg('r');" class="easyui-linkbutton c3" iconCls="icon-no" plain="@SysController.__ThemsType()" style="margin-left:10px">删除</a>
        </div>
    </div>
    <div id="tb2" style="text-align:center">
        <div style="margin:2px">
            <div class="fa fa-file-text-o mylabel"> 输入消息标题、内容或者发送者关键字：</div>
            <input id="searchsendkey" class="easyui-textbox" style="width:200px;height:25px">
            <div class="fa fa-filter mylabel" data-options="plain:true">发送时间从：</div>
            @Html.Partial("_DateSelect", new ViewDataDictionary { { "id", "st2" }, { "d", "-7" } })
            <div class="fa fa-filter mylabel" data-options="plain:true">到：</div>
            @Html.Partial("_DateSelect", ViewData["id"] = "et2")
            <select id="readtype2" class="easyui-combobox" name="state" style="width:80px" data-options="panelHeight:'auto'">
                <option value="-1">全部</option>
                <option value="1">已读</option>
                <option value="0">未读</option>
            </select>
            <a href="javascript:searchSendBox();" class="easyui-linkbutton c2" iconCls="icon-search" plain="@SysController.__ThemsType()" style="margin-left:10px">查询</a>
            <a href="javascript:delMsg('s');" class="easyui-linkbutton c3" iconCls="icon-no" plain="@SysController.__ThemsType()" style="margin-left:10px">删除</a>
        </div>
    </div>
    @Html.Partial("_PublishTool")
    <script src="~/JsApp/MyMsg/index.js"></script>
</body>
</html>

NGZB/Views/MyMsg/_GetMsgInfo.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>消息详情</title>
    @Html.Partial("_JsCss")
    <script>
        $(function () {
            ('@ViewBag.msginfo');
        })
    </script>
</head>
<body>
    <div>
    </div>
</body>
</html>