NGZB/Models/Role.cs
using System.Data;
using Newtonsoft.Json;
using NGZB.Models.Class;

namespace NGZB.Models
{
    public class Role
    {
        public static int Del(string[] roleID)
        {
            ctxDbDataContext ctx = new ctxDbDataContext();
            int suc = 0;
            int? rt = 0;
            for (int i = 0; i < roleID.Length; i++)
            {
                int _roleID = 0;
                int.TryParse(roleID[i], out _roleID);
                ctx.D_NGZB_Role(_roleID, ref rt);
                if (rt == 1)
                {
                    suc = suc + 1;
                }
            }
            return suc;
        }

        public static int Pass(string roleName)
        {
            return DbHelp.SearchNum("NGZB_Role", "roleName='" + roleName + "'");
        }

        public static int Add(string roleName, string roleInfo)
        {
            ctxDbDataContext ctx = new ctxDbDataContext();
            int? rt = 0;
            ctx.I_NGZB_Role(roleName, roleInfo, 0, ref rt);
            if (rt == 1)
            {
                return 1;
            }
            else
            {
                return 0;
            }
        }

        public static string GetComboBox()
        {
            DataTable dt = DbHelp.ExcuteTable("SELECT roleID,roleName FROM NGZB_Role", null, null);
            return JsonConvert.SerializeObject(dt);
        }

        public static string Get(int selectFlag, string key)
        {
            string where = "";
            switch (selectFlag)
            {
                case 1:
                    where = string.Format("(roleName LIKE '%{0}%')", key);
                    break;

                case 2:
                    where = string.Format("roleID IN (SELECT roleID FROM V_NGZB_Role_Item WHERE menuName LIKE '%{0}%')", key);
                    break;

                case 3:
                    where = string.Format("roleID IN (SELECT roleID FROM V_NGZB_Role_User WHERE userName LIKE '%{0}%')", key);
                    break;

                case 4:
                    where = string.Format("roleID IN (SELECT roleID FROM V_NGZB_Role_User WHERE userCode LIKE '%{0}%')", key);
                    break;

                default:
                    where = string.Format("(roleName LIKE '%{0}%')", key);
                    break;
            }
            DataTable dt = DbHelp.ExcuteTable("SELECT * FROM [NGZB_Role]", where, null);
            return JsonConvert.SerializeObject(dt);
        }

        /// <summary>
        /// 添加角色权限
        /// </summary>
        /// <param name="roleId">角色id</param>
        /// <param name="menuID">菜单ID</param>
        /// <param name="appendUserCode">授权人用户名</param>
        /// <returns></returns>
        public static int AddRoleItem(int roleId, int menuID, string appendUserCode)
        {
            ctxDbDataContext ctx = new ctxDbDataContext();
            int? rt = 0;
            ctx.I_NGZB_Role_Item(roleId, menuID, appendUserCode, ref rt);
            return rt == 1 ? 1 : 0;
        }

        public static string GetRoleItem(string roleid)
        {
            DataTable dt = DbHelp.ExcuteTable("SELECT [roleItemID],[menuName],[menuInfo] FROM [V_NGZB_Role_Item]", string.Format("[roleID]={0}", roleid), null);
            return JsonConvert.SerializeObject(dt);
        }

        public static int DelRoleItem(int roleitemID)
        {
            ctxDbDataContext ctx = new ctxDbDataContext();
            int? rt = 0;
            ctx.D_NGZB_Role_Item(roleitemID, ref rt);
            if (rt == 1)
            {
                return 1;
            }
            else
            {
                return 0;
            }
        }

        public static string GetUserRole(int roleID)
        {
            DataTable dt = DbHelp.ExcuteTable("SELECT DISTINCT [roleUserID],[userName],[groupName],[roleAddUser],CONVERT(varchar(100), [addDate], 23) AS [addDate] FROM [V_NGZB_Role_UserInfo]", string.Format("[roleID]={0}", roleID), null);
            return JsonConvert.SerializeObject(dt);
        }

        public static int AddUserRole(int roleid, string[] userCode, string opUser)
        {
            int suc = 0;
            ctxDbDataContext ctx = new ctxDbDataContext();
            int? rt = 0;
            for (int i = 0; i < userCode.Length; i++)
            {
                ctx.I_NGZB_Role_User(roleid, userCode[i], opUser, ref rt);
                if (rt == 1)
                {
                    suc = suc + 1;
                }
            }
            return suc;
        }

        public static int DelUserRole(int roleUserID, string opUser)
        {
            ctxDbDataContext ctx = new ctxDbDataContext();
            int? rt = 0;
            ctx.D_NGZB_Role_User(roleUserID, opUser, ref rt);
            if (rt == 1)
            {
                return 1;
            }
            else
            {
                return 0;
            }
        }

        public static string GetRoleInfo(int roleid)
        {
            DataTable dt = DbHelp.ExcuteTable("SELECT [menuName] FROM [V_NGZB_Role_Item]", string.Format("[roleID]={0}", roleid), null);
            string rtStr = "";
            DbHelp.ExcuteNoQuery(string.Format("UPDATE NGZB_Role SET roleItemCount={0} WHERE roleID={1}", dt.Rows.Count, roleid));
            if (dt.Rows.Count > 0)
            {
                foreach (DataRow row in dt.Rows)
                {
                    rtStr = rtStr + "<li style=\"color:blue\">" + row["menuName"] + "</li>";
                }
                return "<ol>" + rtStr + "</ol>";
            }
            else
            {
                return "没有业务";
            }
        }

        public static string GetRoleUser(int roleid)
        {
            DataTable dt = DbHelp.ExcuteTable("SELECT [userName] FROM [V_NGZB_Role_User]", string.Format("[roleID]={0}", roleid), null);
            string rtStr = "";
            DbHelp.ExcuteNoQuery(string.Format("UPDATE NGZB_Role SET roleUserCount={0} WHERE roleID={1}", dt.Rows.Count, roleid));
            if (dt.Rows.Count > 0)
            {
                foreach (DataRow row in dt.Rows)
                {
                    rtStr = rtStr + "<li style=\"color:blue\">" + row["userName"] + "</li>";
                }
                return "<ol>" + rtStr + "</ol>";
            }
            else
            {
                return "没有用户";
            }
        }
    }
}

NGZB/Controllers/MenuController.cs
using System.Web.Mvc;
using NGZB.Filter;
using NGZB.Models;
using NGZB.Models.Class;

namespace NGZB.Controllers
{
    [LoginPass]
    [CheckUrl]
    public class MenuController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        //-----------------------分割线，以下为无界面或者为子界面的方法，要添加主界面的方法，在此线以上添加--------------------
        public string __GetMenuGroup()
        {
            return Menu.GetParentMenu(0);
        }

        public int __Del(FormCollection form)
        {
            if (form["menuid"] != null)
            {
                int menuid = 0;
                int.TryParse(form["menuid"], out menuid);
                return Menu.Del(menuid);
            }
            else
            {
                return 0;
            }
        }

        [HttpPost]
        public int __Add(FormCollection form)
        {
            if (form["menuparentID"] == null || form["menuImg"] == null || form["modeid"] == null || form["colercssclass"] == null || form["menutype"] == null)
            {
                return 0;
            }
            else
            {
                int menuparentid = 0;
                int modeid = 0;
                int menutype = 0;
                if (int.TryParse(form["menuparentID"], out menuparentid) == false || int.TryParse(form["modeid"], out modeid) == false)
                {
                    return 0;
                }
                else
                {
                    if (int.TryParse(form["menutype"], out menutype) == false)
                    {
                        menutype = 1;
                    }
                    string menuimg = form["menuImg"].Trim();
                    string colercssclass = form["colercssclass"];
                    return Menu.Add(menuparentid, modeid, menutype, menuimg, colercssclass);
                }
            }
        }

        public string __RoleMenu(FormCollection form)
        {
            if (Request.QueryString["roleid"] != null && Request.QueryString["pid"] != null)
            {
                return Menu.RoleMenu(Request.QueryString["roleid"].ToString(), Request.QueryString["pid"].ToString());
            }
            else
            {
                return "";
            }
        }

        public string __GetParentMenu()
        {
            return Menu.GetParentMenu(0);
        }

        [HttpPost]
        public string __GetMenu(FormCollection form)
        {
            int parentID = 0;
            if (form["parentID"] != null)
            {
                int.TryParse(form["parentID"], out parentID);
                return Menu.GetParentMenu(parentID);
            }
            else
            {
                return "[]";
            }
        }

        [HttpPost]
        public int __AddMenuGroup(FormCollection form)
        {
            if (form["menugroupname"] != null)
            {
                string groupName = form["menugroupname"].ToString().Trim();
                string icon = "my_any";
                if (form["menuImg"] != null)
                {
                    icon = form["menuImg"].ToString().Trim();
                }
                return Menu.AddMenuGroup(groupName, icon);
            }
            else
            {
                return -1;
            }
        }

        public ActionResult _Edit(int? menuid, int? menutype)
        {
            ViewBag.menuID = menuid;
            ViewBag.menuType = menutype;
            return View();
        }

        public int __Edit(int? menuid, int? menutype, int? modelid, string menuimg, int? menuorderby, string menucolor, int? parentid)
        {
            if (menuid == null)
            {
                return -1;
            }
            else
            {
                return Menu.Edit(menuid, menutype, modelid, menuimg, menuorderby, menucolor, parentid);
            }
        }
    }
}

NGZB/Controllers/RoleController.cs
using System.Web.Mvc;
using NGZB.Filter;
using NGZB.Models;
using NGZB.Models.Class;

namespace NGZB.Controllers
{
    [LoginPass]
    [CheckUrl]
    public class RoleController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        public ActionResult UserRole()
        {
            ViewBag.modelID = PublishMethod.GetModelID(RouteData);
            return View();
        }

        //-----------------------分割线，以下为无界面或者为子界面的方法，要添加主界面的方法，在此线以上添加--------------------

        public string __GetComboBox()
        {
            return Role.GetComboBox();
        }

        public string __Get(FormCollection form)
        {
            string key = "";
            int selectFlag = 0;
            if (form["key"] != null)
            {
                key = form["key"];
            }
            if (form["f"] != null)
            {
                int.TryParse(form["f"], out selectFlag);
            }
            return Role.Get(selectFlag, key);
        }

        [HttpPost]
        public int __Del(FormCollection form)
        {
            if (form["roleID"] == null)
            {
                return 0;
            }
            else
            {
                string[] roleID = form["roleID"].Split('|');
                return Role.Del(roleID);
            }
        }

        public ActionResult _Add()
        {
            return View();
        }

        [HttpPost]
        public int __Add(FormCollection form)
        {
            string roleName = "";
            string roleInfo = "";
            if (form["roleName"] != null)
            {
                if (form["roleInfo"] != null)
                {
                    roleInfo = form["roleInfo"];
                }
                roleName = form["roleName"];
                return Role.Add(roleName, roleInfo);
            }
            else
            {
                return 0;
            }
        }

        public ActionResult _Edit()
        {
            return View();
        }

        [HttpPost]
        public int __Edit(FormCollection form)
        {
            return 0;
        }

        public int __Pass(FormCollection form)
        {
            if (form["roleName"] != null)
            {
                return Role.Pass(form["roleName"]);
            }
            else
            {
                return 1;
            }
        }

        public string __RoleItem(FormCollection form)
        {
            if (form["roleid"] != null)
            {
                return Role.GetRoleItem(form["roleid"]);
            }
            else
            {
                return "";
            }
        }

        [HttpPost]
        public int __AddRoleItem(FormCollection form)
        {
            if (form["roleid"] != null && form["menuid"] != null)
            {
                NGZB.Models.Object.LoginUser loginuser = new Models.Object.LoginUser();
                string appendUserCode = loginuser.LoginUserName + "(" + loginuser.LoginUserCode + ")";
                int roleid = 0;
                int menuid = 0;
                int suc = 0;
                string[] _menuid = form["menuid"].Split('|');
                if (_menuid.Length > 0 && true == int.TryParse(form["roleid"], out roleid))
                {
                    for (int i = 0; i < _menuid.Length; i++)
                    {
                        if (true == int.TryParse(_menuid[i], out menuid))
                        {
                            if (Role.AddRoleItem(roleid, menuid, appendUserCode) > 0)
                            {
                                suc = suc + 1;
                            }
                        }
                    }
                    return suc;
                }
                else
                {
                    return -1;
                }
            }
            else
            {
                return -1;
            }
        }

        public int __DelRoleItem(FormCollection form)
        {
            if (form["roleItemID"] != null)
            {
                int suc = 0;
                string[] _roleitemid = form["roleItemID"].Split('|');
                if (_roleitemid.Length > 0)
                {
                    int roleitemid = 0;
                    for (int i = 0; i < _roleitemid.Length; i++)
                    {
                        int.TryParse(_roleitemid[i], out roleitemid);
                        if (Role.DelRoleItem(roleitemid) == 1)
                        {
                            suc = suc + 1;
                        }
                    }
                    return suc;
                }
                else
                {
                    return 0;
                }
            }
            else
            {
                return 0;
            }
        }

        public string __GetUserRole(FormCollection form)
        {
            int roleid = 0;
            if (form["roleid"] != null)
            {
                int.TryParse(form["roleid"], out roleid);
            }
            return Role.GetUserRole(roleid);
        }

        public int __AddUserRole(FormCollection form)
        {
            if (form["usercode"] != null && form["roleid"] != null)
            {
                int roleid = 0;
                int.TryParse(form["roleid"], out roleid);
                string[] userCode = form["usercode"].Split('|');
                Models.Object.LoginUser loginuser = new Models.Object.LoginUser();
                string opUser = loginuser.LoginUserName + "(" + loginuser.LoginUserCode + ")";
                return Role.AddUserRole(roleid, userCode, opUser);
            }
            else
            {
                return -1;
            }
        }

        public int __DelUserRole(FormCollection form)
        {
            int suc = 0;
            if (form["roleUserID"] != null)
            {
                string[] _roleUserID = form["roleUserID"].Split('|');
                int roleUserID = 0;
                Models.Object.LoginUser loginuser = new Models.Object.LoginUser();
                string opUser = loginuser.LoginUserName + "(" + loginuser.LoginUserCode + ")";
                for (int i = 0; i < _roleUserID.Length; i++)
                {
                    int.TryParse(_roleUserID[i], out roleUserID);

                    if (Role.DelUserRole(roleUserID, opUser) == 1)
                    {
                        suc = suc + 1;
                    }
                }
            }
            else
            {
                suc = -1;
            }
            return suc;
        }

        public string __GetRoleInfo(FormCollection form)
        {
            if (Request.QueryString["roleID"] != null)
            {
                int roleid = 0;
                int.TryParse(Request.QueryString["roleID"], out roleid);
                return Role.GetRoleInfo(roleid);
            }
            else
            {
                return "";
            }
        }

        public string __GetRoleUser(FormCollection form)
        {
            if (Request.QueryString["roleID"] != null)
            {
                int roleid = 0;
                int.TryParse(Request.QueryString["roleID"], out roleid);
                return Role.GetRoleUser(roleid);
            }
            else
            {
                return "";
            }
        }
    }
}

NGZB/Views/Role/Index.cshtml
@using NGZB.Controllers

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>角色管理</title>
    @Html.Partial("_JsCss")
    @{ var objTokenKey = SysController.__TokenKey(); }
    <script>
        var url_getroleinfo = '@Url.Action("__GetRoleInfo", "Role",objTokenKey)';
        var url_getroleuser = '@Url.Action("__GetRoleUser", "Role",objTokenKey)';
        var url_add = '@Url.Action("_Add", "Role",objTokenKey)';
        var url_edit = '@Url.Action("_Edit", "Role",objTokenKey)';
        var url_del = '@Url.Action("__Del", "Role", objTokenKey)';
    </script>
</head>
<body>
    <table id="dg" class="easyui-datagrid" title="角色管理" style="width:100%"
           data-options="@SysController.__PublishTool(),iconCls:'icon-my_user',fit:true,rownumbers:true,singleSelect:true,pagination:true,pageSize:@SysController.__PageSize(),loadFilter:pagerFilter,url: '@Url.Action("__Get","Role", objTokenKey)',toolbar:'#tb',fitColumns:true,striped:true,border:false">
        <thead>
            <tr style="width:100%">
                <th data-options="field:'ck',checkbox:true" align="center"></th>
                <th data-options="field:'roleID',width:60,align:'center',halign:'center'">角色ID</th>
                <th data-options="field:'roleName',width:150,align:'center',halign:'center'">角色名称</th>
                <th data-options="field:'roleInfo',width:400,align:'left',halign:'center'">角色功能描述</th>
                <th data-options="field:'roleItemCount',width:80,align:'center',halign:'center',formatter:roleformater">权限数量</th>
                <th data-options="field:'roleUserCount',width:80,align:'center',halign:'center',formatter:userformater">用户数量</th>
            </tr>
        </thead>
    </table>
    <div id="tb">
        <div style="margin:2px">
            <a href="javascript:;" class="easyui-linkbutton" iconAlign="@SysController.__IconAlign()" iconCls="icon-add" plain="@SysController.__ThemsType()" onclick="add();">新建角色</a>
            <a href="javascript:;" class="easyui-linkbutton" iconAlign="@SysController.__IconAlign()" iconCls="icon-edit" plain="@SysController.__ThemsType()" onclick="edit();">业务管理</a>
            <a href="javascript:;" class="easyui-linkbutton" iconAlign="@SysController.__IconAlign()" iconCls="icon-remove" plain="@SysController.__ThemsType()" onclick="delconfirm();">删除角色</a>
            <div class="fa fa-file-text-o mylabel" style="padding-left:15px"> 输入查询条件：</div>
            <input id="searchkey" class="easyui-textbox" style="width:160px;height:25px">
            <select id="f" class="easyui-combobox" name="state" data-options="panelHeight:'auto'" style="width:100px;height:26px;">
                <option value="1" selected>按角色名称</option>
                <option value="2">按权限名称</option>
                <option value="3">按用户姓名</option>
                <option value="4">按用户名</option>
            </select>
            <a href="javascript:;" class="easyui-linkbutton c2" iconCls="icon-search" plain="@SysController.__ThemsType()" onclick="search();">查询</a>
        </div>
    </div>
    @Html.Partial("_PublishTool")
    <script src="~/JsApp/Role/index.js"></script>
</body>
</html>

NGZB/Views/Role/UserRole.cshtml
@using NGZB.Controllers

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>用户角色授权</title>
    @Html.Partial("_JsCss")
    @{ var objTokenKey = SysController.__TokenKey(); }
    <script>
        var url_adduserrole = '@Url.Action("__AddUserRole","Role", objTokenKey)';
        var url_deluserrole = '@Url.Action("__DelUserRole", "Role", objTokenKey)';
        var url_getusergroup = '@Url.Action("__GetUserGroup", "User",objTokenKey)';
    </script>
</head>
<body>
    <table id="dg" class="easyui-datagrid" title="用户角色授权" style="width:100%"
           data-options="@SysController.__PublishTool(),iconCls:'icon-my_menumanage',fit:true,rownumbers:false,singleSelect:false,pagination:true,pageSize:@SysController.__PageSize(),loadFilter:pagerFilter,url: '@Url.Action("__GetUserRole","Role",objTokenKey)',toolbar:'#tb',fitColumns:true,striped:true,border:false">
        <thead>
            <tr style="width:100%">
                <th data-options="field:'ck',checkbox:true" align="center"></th>
                <th field="roleUserID" width="100" align="center">ID</th>
                <th field="userName" width="80" align="center">用户姓名</th>
                <th field="groupName" width="200" align="center">所属于部门</th>
                <th field="roleAddUser" width="80" align="center">授权人</th>
                <th field="addDate" width="140" align="center">授权日期</th>
            </tr>
        </thead>
    </table>
    <div id="tb">
        <div style="margin:2px">
            <div class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-my_user'" style="enable-background:accumulate">
                选择角色
            </div>
            <input id="roleID" class="easyui-combobox" name="role" data-options="url:'@Url.Action("__GetComboBox","Role", objTokenKey)',method:'get',required:false,valueField:'roleID',textField:'roleName',panelHeight:'auto'">

            <div class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-my_dpmap'" style="enable-background:accumulate">
                选择单位
            </div>
            <input id="groupID" class="easyui-combotree" data-options="url:'@Url.Action("__Get","Group",objTokenKey)',method:'get',lines:'true',panelHeight:'auto',iconCls:'icon-my_dpmap',iconAlign:'right',required:false,onSelect:function(node){search(node.id);}" style="width:150px;">

            <div class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-man'" style="enable-background:accumulate">
                选择用户
            </div>
            <input id="userCode" class="easyui-combobox" data-options="url:'@Url.Action("__GetUserGroup","User", objTokenKey)', method:'get',valueField:'userCode',textField:'userName',panelHeight:'auto',multiple:true,required:true">

            <a href="javascript:add();" class="easyui-linkbutton" iconAlign="@SysController.__IconAlign()" iconCls="icon-add" plain="@SysController.__ThemsType()">分配角色</a>
            <a href="javascript:del();" class="easyui-linkbutton" iconAlign="@SysController.__IconAlign()" iconCls="icon-remove" plain="@SysController.__ThemsType()">撤销角色</a>
        </div>
    </div>
    @Html.Partial("_PublishTool")
    <script src="~/JsApp/Role/userrole.js"></script>
</body>
</html>

NGZB/Views/Role/_Add.cshtml
@using NGZB.Controllers

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>添加角色</title>
    @Html.Partial("_JsCss")
    @{ var objTokenKey = SysController.__TokenKey(); }
    <script>
        var url_add = '@Url.Action("__Add","Role", objTokenKey)';
        var url_pass = '@Url.Action("__Pass", "Role", objTokenKey)';
        var checkPass = '1';
    </script>
</head>
<body>
    <div class="easyui-panel" title="添加角色" style="width:300px" data-options="iconCls:'icon-my_user'">
        <div style="padding:10px 10px 10px 10px">
            <div id="ff" class="easyui-form" data-options="novalidate:true">
                <table cellpadding="5">
                    <tr>
                        <td class="rightTD">角色名称:</td>
                        <td><input id="roleName" class="easyui-textbox" type="text" name="userCode" data-options="required:true,iconCls:'icon-my_user',iconAlign:'right'"></td>
                    </tr>
                    <tr>
                        <td class="rightTD">角色描述:</td>
                        <td><input id="roleInfo" class="easyui-textbox" name="message" data-options="multiline:true" style="height:120px"></td>
                    </tr>
                </table>
            </div>
            <div style="text-align:center;padding:5px">
                <a href="javascript:void(0)" class="easyui-linkbutton c2" data-options="iconCls:'icon-add'" onclick="submitForm()">添加</a>
                <a href="javascript:void(0)" class="easyui-linkbutton c4" data-options="iconCls:'icon-no'" onclick="clearForm()">清空</a>
            </div>
        </div>
    </div>
    <script src="~/JsApp/Role/_add.js"></script>
</body>
</html>

NGZB/Views/Role/_Edit.cshtml
@using NGZB.Controllers
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>角色权限管理</title>
    @Html.Partial("_JsCss")
    @{ var objTokenKey = SysController.__TokenKey(); }
    <script>
        var isnull = 0;
        var url_rolemenu = '@Url.Action("__RoleMenu", "Menu",objTokenKey)';
        var url_addroleitem = '@Url.Action("__AddRoleItem", "Role",objTokenKey)';
        var url_delroleitem = '@Url.Action("__DelRoleItem", "Role", objTokenKey)';;
    </script>
</head>
<body>
    <table id="dg" class="easyui-datagrid" title="角色权限管理" style="width:100%"
           data-options="iconCls:'icon-my_plugin',fit:true,rownumbers:true,singleSelect:true,pagination:true,pageSize:10,url:'@Url.Action("__RoleItem","Role",objTokenKey)',method:'post',toolbar:'#tb',fitColumns:true">
        <thead>
            <tr style="width:100%">
                <th data-options="field:'ck',checkbox:true" align="center"></th>
                <th data-options="field:'roleItemID',width:60,align:'center',halign:'center'">细项ID</th>
                <th data-options="field:'menuName',width:150,align:'center',halign:'center'">菜单名称</th>
                <th data-options="field:'menuInfo',width:400,align:'left',halign:'center'">菜单功能描述</th>
            </tr>
        </thead>
    </table>
    <div id="tb" style="padding:2px">
        <div>
            <div class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-my_user'" style="enable-background:accumulate">选择角色</div>
            <input id="roleID" class="easyui-combobox" name="role" data-options="url:'@Url.Action("__GetComboBox","Role",objTokenKey)',method:'get',valueField:'roleID',textField:'roleName',onLoadSuccess:function(data){selectroleID(),searchmenu();serchrolemenu();},panelHeight:'auto'">
            <div class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-my_menugroup'" style="enable-background:accumulate">选择菜单分组</div>
            <input id="menuGrop" class="easyui-combobox" name="role" data-options="url:'@Url.Action("__GetMenuGroup","Menu",objTokenKey)',method:'get',valueField:'menuID',textField:'menuName',onLoadSuccess:function(data){selectmenugroup();searchmenu();},panelHeight:'auto'">
            <div class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-my_menumanage'" style="enable-background:accumulate">选择菜单</div>
            <input id="menuID" class="easyui-combobox" name="role" data-options="url:'@Url.Action("__RoleMenu","Menu",objTokenKey)',method:'get',valueField:'menuID',editable:false ,multiple:true,textField:'menuName', onLoadSuccess:function(data){selectmenu();},panelHeight:'auto'">
            <a id="addallow" href="javascript:add();" class="easyui-linkbutton" iconAlign="top" iconCls="icon-ok" plain="@SysController.__ThemsType()">添加授权</a>
            <a id="delallow" href="javascript:delconfirm();" class="easyui-linkbutton" iconAlign="top" iconCls="icon-my_del" plain="@SysController.__ThemsType()">删除授权</a>
        </div>
    </div>
    <script src="~/JsApp/Role/_edit.js"></script>
</body>
</html>